version: 2
updates:

  # Maintain dependencies for maven in v3-main branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v3-main"

  # Maintain dependencies for GitHub Actions in v3-main
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`.
    # (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "v3-main"

    # Maintain dependencies for maven in v2-main branch
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v2-main"

  # Maintain dependencies for GitHub Actions in v2-main
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`.
    # (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "v2-main"
